// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvfnpjawxwmxfjbaguxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2Zm5wamF3eHdteGZqYmFndXh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTQxNjUsImV4cCI6MjA2NTU3MDE2NX0.wPB1zSicw0fq9akrI1ETteC1K3AjE7vzt6VrIrbvoQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);